export interface SeedCompany {
  name: string;
  url: string;
  notes?: string;
  renderMode?: 'static' | 'browser';
}

export const SEED_COMPANIES: SeedCompany[] = [
  { name: 'Fiskars', url: 'https://fiskars.wd3.myworkdayjobs.com/en-US/FiskarsGroup?locationCountry=0afb2fa656da42e8bfb6d47bd24a26fa', notes: 'Workday', renderMode: 'browser' },
  { name: 'Marimekko', url: 'https://company.marimekko.com/careers/open-jobs/' },
  { name: 'Wolt', url: 'https://careers.wolt.com/en/jobs' },
  { name: 'Supercell', url: 'https://supercell.com/en/careers/' },
  { name: 'Metacore', url: 'https://metacoregames.com/open-positions' },
  { name: 'Zalando', url: 'https://jobs.zalando.com/en/jobs?location=Helsinki' },
  { name: 'Rovio', url: 'https://www.rovio.com/open-positions/' },
  { name: 'Sievo', url: 'https://sievo.com/careers#openpositions' },
  { name: 'Smartly', url: 'https://job-boards.greenhouse.io/smartlyio', notes: 'Greenhouse', renderMode: 'static' },
  { name: 'RELEX', url: 'https://www.relexsolutions.com/careers/#open-positions' },
  { name: 'Supermetrics', url: 'https://supermetrics.com/careers#open-positions' },
  { name: 'Reaktor', url: 'https://www.reaktor.com/careers/all-open-positions' },
  { name: 'Swappie', url: 'https://careers.swappie.com/jobs' },
  { name: 'Solibri', url: 'https://www.solibri.com/careers' },
  { name: 'Columbia Road', url: 'https://www.columbiaroad.com/careers#form' },
  { name: 'Futurice', url: 'https://futurice.com/careers/open-positions?office=Helsinki' },
  { name: 'One Click LCA', url: 'https://careers.oneclicklca.com/jobs' },
  { name: 'Qt', url: 'https://www.qt.io/careers?country=Finland' },
  { name: 'Hoxhunt', url: 'https://careers.hoxhunt.com/jobs' },
  { name: 'AlphaSense', url: 'https://www.alpha-sense.com/careers/#openings' },
  { name: 'Visma', url: 'https://www.visma.com/careers/open-positions?countries=Finland' },
  { name: 'Unity', url: 'https://careers.unity.com/find-position?location=helsinki' },
  { name: 'Sanoma', url: 'https://www.sanoma.fi/en/about-us/careers/open-positions/' },
  { name: 'Solita', url: 'https://www.solita.fi/join-us/?country=finland' },
  { name: 'Documill', url: 'https://documill.com/careers/' },
  { name: 'Vincit', url: 'https://www.vincit.com/careers' },
  { name: 'IKEA', url: 'https://jobs.ikea.com/en/search-jobs/Finland/22908/2/660013/64/26/25/2' },
  { name: 'Eficode', url: 'https://career.eficode.com/jobs?location=Helsinki+-+Finland&split_view=true', notes: 'Likely Teamtailor' },
  { name: 'Yousician', url: 'https://yousician.com/careers' },
  { name: 'Evermade', url: 'https://www.evermade.fi/about/careers/' },
  { name: 'Vaimo', url: 'https://careers.vaimo.com/jobs?country=Finland&split_view=true', notes: 'Likely Teamtailor' },
  { name: 'Finnish Design Shop', url: 'https://finnishdesignshop.teamtailor.com/jobs', notes: 'Teamtailor', renderMode: 'static' },
  { name: 'Nomentia', url: 'https://www.nomentia.com/company/careers' },
  { name: 'Visual Components', url: 'https://www.visualcomponents.com/careers/' },
  { name: 'Kone', url: 'https://careers.kone.com/en/find-jobs/?search=&country=Finland&pagesize=20#results' },
  { name: 'Aibidia', url: 'https://careers.aibidia.com/' },
  { name: 'Frends', url: 'https://careers.frends.com/jobs' },
  { name: 'Etteplan', url: 'https://www.etteplan.com/careers/open-positions/apply-now/?country=finland' },
  { name: 'Inven', url: 'https://careers.inven.ai/jobs' },
  { name: 'Aiven', url: 'https://aiven.io/careers/job?office=Finland' },
  { name: 'Swarmia', url: 'https://www.swarmia.com/careers/#open-positions' },
  { name: 'Nosto', url: 'https://careers.nosto.com/jobs' },
  { name: 'Virta', url: 'https://liikennevirtaoy.teamtailor.com/jobs', notes: 'Teamtailor' },
  { name: 'Fixably', url: 'https://careers.fixably.com/' },
  { name: 'Gofore', url: 'https://gofore.com/en/careers/' },
  { name: 'Nitor', url: 'https://nitor.com/en/people' },
  { name: 'Solteq', url: 'https://www.solteq.com/en/careers#open-positions' },
  { name: 'M-files', url: 'https://apply.workable.com/m-files/?lng=en', notes: 'Workable', renderMode: 'browser' },
  { name: 'Varjo', url: 'https://varjo.com/jobs' },
  { name: 'HappySignals', url: 'https://www.happysignals.com/careers#open-positions' },
  { name: 'Verda', url: 'https://verda.com/jobs' },
  { name: 'Kempower', url: 'https://kempower.com/careers/#open-position' },
  { name: 'Tietoevry', url: 'https://careers.tietoevry.com/jobs?options=288&page=1' },
  { name: 'Veikkaus', url: 'https://www.veikkausgroup.com/en/careers/open-positions' },
  { name: 'IQM', url: 'https://iqm.teamtailor.com/jobs?country=Finland&split_view=true', notes: 'Teamtailor' },
  { name: 'Orion Pharma', url: 'https://fa-esaq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/OrionCareers/jobs', notes: 'Oracle Cloud', renderMode: 'browser' },
  { name: 'Stockmann', url: 'https://careers.stockmann.com/open-jobs/' },
  { name: 'Mapbox', url: 'https://www.mapbox.com/careers' },
  { name: 'Meetingpackage', url: 'https://meetingpackage.com/web/careers' },
  { name: 'Holvi', url: 'https://holvi.teamtailor.com/jobs', notes: 'Teamtailor' },
  { name: 'Framery', url: 'https://framery.com/en/careers/' },
  { name: 'UpCloud', url: 'https://upcloud.teamtailor.com/#jobs', notes: 'Teamtailor' },
  { name: 'Bou', url: 'https://bou.co/careers#open-positions' },
  { name: 'Upright Project', url: 'https://www.uprightproject.com/careers' },
  { name: 'Capalo', url: 'https://capaloai.com/join-us/' },
  { name: 'Academic Work', url: 'https://www.academicwork.fi/avoimet-tyopaikat' },
  { name: 'CHAOS', url: 'https://www.chaosarchitects.com/careers' },
  { name: 'Antler', url: 'https://antler.applytojob.com/apply', notes: 'JazzHR', renderMode: 'browser' },
  { name: 'Finago', url: 'https://finago.com/open-positions/' },
  { name: 'SD Worx', url: 'https://careers.sdworx.com/jobs?country=Finland' },
  { name: 'WithSecure', url: 'https://www2.withsecure.com/en/about-us/careers-at-withsecure/open-jobs' },
  { name: 'Sellforte', url: 'https://careers.sellforte.com/jobs' },
  { name: 'MVision', url: 'https://mvision.ai/about/careers/' },
  { name: 'Vaisala', url: 'https://careers.vaisala.com/search/' },
  { name: 'Tuxera', url: 'https://tuxera.breezy.hr/?country=Finland', notes: 'Breezy HR', renderMode: 'browser' },
  { name: 'F-Secure', url: 'https://company.f-secure.com/en/careers#latest-jobs' },
  { name: 'Tracklution', url: 'https://careers.tracklution.com/jobs' },
  { name: 'Treon', url: 'https://careers.treon.fi/jobs' },
  { name: 'Realm', url: 'https://www.withrealm.com/about-us#careers' },
  { name: 'Duunitori', url: 'https://duunitori.fi/tyopaikat?haku=marketing&order_by=date_posted', notes: 'Job board — keyword in URL already' },
  { name: 'Groweo', url: 'https://careers.groweo.com/jobs' },
  { name: 'N.Rich', url: 'https://careers.nrich.io/jobs' },
  { name: 'Sumsub', url: 'https://careers.sumsub.com/jobs?region=EU' },
  { name: 'Suunto', url: 'https://www.suunto.com/fi-fi/Tietoa-Suunnosta/Yhtiotiedot/Careers/' },
  { name: 'Staria', url: 'https://www.stariacareers.com/jobs' },
  { name: 'Oura', url: 'https://ouraring.com/careers' },
  { name: 'Novo Nordisk', url: 'https://www.novonordisk.com/careers/find-a-job/career-search-results.html?countries=Finland' },
  { name: 'Wärtsilä', url: 'https://careers.wartsila.com/search/?optionsFacetsDD_country=FI', notes: 'SAP SuccessFactors', renderMode: 'static' },
  { name: 'Fortum', url: 'https://jobs.fortum.com/search/?optionsFacetsDD_country=FI', notes: 'Likely SAP SuccessFactors' },
  { name: 'Bolt', url: 'https://bolt.eu/en/careers/positions/?location%5B0%5D=Finland-Helsinki' },
];
